### ISSUE TITLE
Setting theme via path

### ISSUE THREAD

**Issue by shamindras** [catppuccin/lazygit#2]
Thank you for creating this lazygit theme!

I followed the [instructions](https://github.com/catppuccin/lazygit/tree/06f59293af3de63621f3de946f58e4fe3b60a8f0#usage) and tried to do the following in `~/.config/lazygit/config.yml`:

```yml
gui:
  theme:
    - "$HOME/.config/lazygit/themes/catpuccin/latte.yml"
os:
  editCommand: "vim"
  editCommandTemplate: "{{editor}} +{{line}} -- {{filename}}"
  openCommand: "open {{filename}}"
```

but got the following `yaml` parsing error when reloading lazygit

```bash
> lazygit
2022/12/30 22:30:45 The config at `/Users/shamindras/.config/lazygit/config.yml` couldn't be parsed, please inspect it before opening up an issue.
yaml: unmarshal errors:
  line 3: cannot unmarshal !!seq into config.ThemeConfig
```

What is the correct way to reference the `latte.yml` file in the `config.yml`? Or do the contents of the `latte.yml` need to be copy-pasted directly under the `theme:` yaml key?
