### ISSUE TITLE
support for `inactiveViewSelectedLineBgColor` ; `markedBaseCommitFgColor` and `markedBaseCommitBgColor`

### ISSUE THREAD

**Issue by xfzv** [catppuccin/lazygit#44]
From LazyGit default config ([1](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md?plain=1#L125-L127) ; [2](https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md?plain=1#L137-L143))

```yml
# Background color of selected line when view doesn't have focus.
    inactiveViewSelectedLineBgColor:
      - bold

# Foreground color of marked base commit (for rebase)
    markedBaseCommitFgColor:
      - blue

    # Background color of marked base commit (for rebase)
    markedBaseCommitBgColor:
      - yellow
```
